### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by glueckpress** [WPMeetupHamburg/WP_Topics_Poll-_Submit_Vote_Argue#3]
Typisch Zuspätkommer, bemerkt erstmal das Unwichtigste: den Repo-Namen.
Es ist gängige Praxis, Plugin/Theme-Repos in Kleinschreibung zu benennen, genau wie Plugin-Ordner in einer WordPress-Installation.
Man kann Repos bei GitHub umbenennen – mit [etwas Fingerspitzengefühl](https://help.github.com/articles/renaming-a-repository). ;)

**Comment by Drivingralle** [comment]
Das scheint ja ohne große Fehler abzulaufen. Wenn du willst.
